# SonarQube – staticweb (HTML/CSS/JS im Repository-Root)
sonar.projectKey=staticweb
sonar.projectName=staticweb

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/.git/**,**/Jenkinsfile
